export declare class DagreD3Renderer {
    private static data;
    private static graph;
    private static containerId;
    private static containerElement;
    private static container;
    private static group;
    private static zoom;
    private static zoomInMultiplicator;
    private static zoomOutMultiplicator;
    private static render;
    private static dispatch;
    static initialize(containerElement: any, data: Object, options?: Object): void;
    static renderGraph(options?: Object): void;
    static fit(delay?: number): void;
    static zoomIn(delay?: number): void;
    static zoomOut(delay?: number): void;
    private static flush();
    private static setParameters(containerElement, data, options);
    private static setEvents();
    private static setGraphClickEventListener();
    private static setShapes();
    private static createHexagon(parent, bbox, node);
    private static formatNodes();
    private static formatNode(nodeId);
    private static setNodeShape(node);
    private static setNodeStyle(node);
    private static setNodeColor(node);
    private static formatEdges();
    private static formatEdge(edge);
    private static setEdgeStyle(edge);
    private static setEdgeColor(edge);
    private static constructGraph();
    private static setNodesEvents();
    private static setEdgesEvents();
    private static formatText();
    private static setZoom();
    private static setWidthAndHeight();
}
